name: ee627
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - certifi=2020.6.20
  - click=7.1.2
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - expat=2.2.10
  - ffmpeg=4.0.2
  - fontconfig=2.13.1
  - freeglut=3.2.1
  - freetype=2.10.4
  - glib=2.66.1
  - gmp=6.1.2
  - gnutls=3.5.19
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.17.0
  - joblib=0.17.0
  - jpeg=9d
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - kiwisolver=1.3.1
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.0.4
  - ncurses=6.2
  - nettle=3.3
  - nltk=3.5
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - opencv=3.4.2
  - openh264=1.8.0
  - openssl=1.1.1h
  - pandas=1.1.3
  - parso=0.8.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=20.3.3
  - pixman=0.38.0
  - prompt-toolkit=3.0.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py-opencv=3.4.2
  - pygments=2.7.4
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - readline=8.1
  - regex=2020.10.15
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.50.2
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.36.2
  - x264=1!152.20180806
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.5
